logging:
  level:
    root: info
    com.aorise: debug
  file: logs/${spring.application.name}.log
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.53.204.212:3306/cloud_file?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web
mybatis:
  type-aliases-package: com.aorise.file.model
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true
security:
  oauth2:
    resource:
      user-info-uri: http://127.0.0.1:8080/api-o/user-me
      prefer-token-info: false
file:
  local:
    path: d:/localFile
    prefix: /statics
    urlPrefix: http://127.0.0.1:8080/api-f${file.local.prefix}
  aliyun:
    endpoint: xxx
    accessKeyId: AKIDd0vZy9NuHNCyIWwZLvEIemeqBGPvbFen
    accessKeySecret: 2h6F8kHbfSAettcIlxslOkslbDYcdOs7
    bucketName: cloud-service-1258562762
    domain: https://cloud-service-1258562762.cos.ap-chengdu.myqcloud.com
    region: ap-chengdu
